### ISSUE TITLE
Fix the height mash of call-to-action

### ISSUE THREAD

**Issue by NSkelsey** [ldemarest/ombuds-home#8]
The div is not forced below the logo because of the use of vertical height:

``` css
.landing .main-view {
    height: 55.5vh;
}
```

A simple fix might just be (with a media query for smaller screens):

``` css
.landing .main-view {
    height: 400px;
}
```
